### ISSUE TITLE
Something went wrong while using the plugin “soundflower”

### ISSUE THREAD

**Issue by promisexnothing** [karaggeorge/kap-soundflower#14]
undefined

**macOS version:**    High Sierra (10.13)
**Kap version:**      3.3.2

```
Something went wrong while using the plugin “soundflower”

Error: Command was killed with SIGABRT (Aborted): /Users/aaron/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/audio-devices input set 
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/aaron/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/audio-devices
  Reason: image not found
    at makeError (/macos-audio-devices/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/macos-audio-devices/node_modules/execa/index.js:114:26)
    at async module.exports.<computed> (/macos-audio-devices/index.js:10:20)
    at async Object.didStopRecording (/kap-soundflower/index.js:103:3)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:7
    at async Promise.all (index 2)
    at async cleanup (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:74:3)
```

**Comment by promisexnothing** [comment]
Hello, I am not sure why I am getting this error. I'm also not able to select and record from my internal speakers. Can anyone help?
