### ISSUE TITLE
Something went wrong while using the plugin “soundflower”

### ISSUE THREAD

**Issue by HunterMeyer** [karaggeorge/kap-soundflower#34]
**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.2

```
Something went wrong while using the plugin “soundflower”

Error: 27G1G4 is not an input device
    at throwIfStderr (/macos-audio-devices/index.js:22:11)
    at module.exports.<computed> (/macos-audio-devices/index.js:11:12)
    at async Object.willStartRecording (/kap-soundflower/index.js:97:3)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:7
    at async Promise.all (index 0)
    at async Object.startRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:148:3)
```

![Screen Shot 2021-02-17 at 11 39 13 AM](https://user-images.githubusercontent.com/4690516/108236324-c5fe6400-7114-11eb-8897-8e9f9b685996.png)

It looks like Soundflower is trying to treat "27G1G4" (this is for my monitor's speakers) as an input device, though it is only output.

I wish I could, but haven't been able to remove this device.

**Comment by karaggeorge** [comment]
Hmm looks like it's passed as an input device to Kap. Can you make sure you either have no input device selected or a microphone?

**Comment by HunterMeyer** [comment]
@karaggeorge I have two input devices: internal mic (MacBook Pro Microphone) and headphone mic (Mpow H12 1).
