### ISSUE TITLE
Something went wrong while using the plugin “soundflower”

### ISSUE THREAD

**Issue by dan2k3k4** [karaggeorge/kap-soundflower#45]
Tried to screencapture with system audio but got 2 errors, one for Key Cast but there's already an issue for that [here](https://github.com/wulkano/Kap/issues/986) and then this one which it said I should create an issue for and directed me here.

**macOS version:**    Big Sur (11)
**Kap version:**      3.3.2

```
Something went wrong while using the plugin “soundflower”

Error: Command failed with exit code 1: /Users/dan/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/audio-devices input set 78
No device exists with id 78
    at makeError (/execa/lib/error.js:59:11)
    at handlePromise (/execa/index.js:114:26)
    at async module.exports.<computed> (/macos-audio-devices/index.js:10:20)
    at async Object.didStopRecording (/kap-soundflower/index.js:103:3)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:7
    at async Promise.all (index 2)
    at async cleanup (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:74:3)
```

**Comment by dan2k3k4** [comment]
Closing as literally all issues are the same
